.TH MOJOSETUP "1" "October 2015"

.SH NAME
MojoSetup \- a portable, flexible installation application

.SH SYNOPSIS
.B mojosetup
.br
.B mojosetup \fR--help

.SH DESCRIPTION
.B mojosetup
is a little helper script that copies all files required to build a MojoSetup
installer into a `mojosetup' subdirectory of the current working directory.

.SH "See also"
.BR mojosetup (7)

